#!/bin/bash

# officially recommended hack to enable Port Forwarding for KVM/QEMU VMs for default network setting

if [ "${2}" = "started" ]; then
	# Permenantly add NEW state to LIBVIRT_FWI forward rule
	STATE=NEW
	CHAIN=LIBVIRT_FWI
	IPTCMD="iptables -L $CHAIN -v -n"
	FILTERCMD="grep -v -e Chain -e pkts -e reject-with -e $STATE"
	while $IPTCMD | grep ESTABLISHED | grep -v $STATE >/dev/null
	do
		IF=$($IPTCMD | $FILTERCMD | awk '{print $7}' | head -n1)
		NET=$($IPTCMD | $FILTERCMD | awk '{print $9}' | head -n1)
		/sbin/iptables -D $CHAIN -o $IF -d $NET -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
		/sbin/iptables -I $CHAIN 1 -o $IF -d $NET -m conntrack --ctstate $STATE,RELATED,ESTABLISHED -j ACCEPT
	done

	echo "ACTION=start" > /etc/libvirt/."$1".conf
	systemctl restart vmportforward@"$1".service || :
fi

if [ "${2}" = "release" ]; then
	if grep "ACTION=" /etc/libvirt/."$1".conf > /dev/null; then
		sed -e 's,ACTION=.*,ACTION=stop,g' -i /etc/libvirt/."$1".conf
	else
		echo "ACTION=stop" > /etc/libvirt/."$1".conf
	fi
	systemctl restart vmportforward@"$1".service || :
fi

