#!/bin/bash
# vmportforward: 2345 20 80
# description: Set port forwarding rules for KVM VMs to iptables

# Source function library.
if [ -f /etc/init.d/functions ]; then
       . /etc/init.d/functions
fi

VM=${2:-}
VM_IP=${3:-}
VM_PORT=${4:-22}
CONN="virsh -c qemu:///system"

start() {
	if [ -n "$VM" ]; then
		# Gets VM's IP if none is passed in and calculate forward port
		# on the KVM HOST = 22000 + 4th number of the VM's IP4 address
		while [ -z "$VM_IP" ]; do
			sleep 1
			VM_IP=$($CONN "domifaddr $VM" | grep -e ipv4 | awk '{print $4}' | awk -F'/' '{print $1}')
		done
	fi

	HOST_PORT=$((${VM_IP##*.}+22000))
	# add new entries
	echo "Add PREROUTING entry for IP: $VM_IP Port: $VM_PORT"
	/sbin/iptables -t nat -I PREROUTING 1 -p tcp --dport $HOST_PORT -j DNAT --to-destination $VM_IP:$VM_PORT
	# update VM's IP argument in the environment file of vmportforward@.service
	if grep "IP=" /etc/libvirt/."$VM".conf > /dev/null; then
		sed -e "s,IP=.*,IP=${VM_IP},g" -i /etc/libvirt/."$VM".conf
	else
		echo "IP=$VM_IP" >> /etc/libvirt/."$VM".conf
	fi
}

stop() {
	# remove already existing entry in the NAT's PREROUTING list first
	echo "Delete PREROUTING entry for IP: $VM_IP Port: $VM_PORT"
	HOST_PORT=$((${VM_IP##*.}+22000))
	/sbin/iptables -t nat -D PREROUTING -p tcp --dport $HOST_PORT -j DNAT --to-destination $VM_IP:$VM_PORT
	rm /etc/libvirt/."$VM".conf
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0

